#!/usr/bin/env python

from __future__ import print_function, unicode_literals
from PyInquirer import prompt, print_json
from PyInquirer import Validator, ValidationError

import os
import sys
sys.path.append(os.getcwd() + "/zigdiggity")
import pprint
import time
import argparse
from scapy.layers.dot15d4 import *
from scapy.layers.zigbee import *

from zigdiggity.radios.raspbee_radio import RaspbeeRadio
from zigdiggity.radios.observer_radio import ObserverRadio
from zigdiggity.observers.wireshark_observer import WiresharkObserver
from zigdiggity.interface.console import *
from zigdiggity.interface.components.logo import Logo
import zigdiggity.crypto.utils as crypto_utils
from zigdiggity.misc.actions import *

class NumberValidator(Validator):
    def validate(self, document):
        try:
            int(document.text)
        except ValueError:
            raise ValidationError(
                message='Please enter a number',
                cursor_position=len(document.text))  # Move cursor to end
             
logo = Logo()
logo.print()

print_info("Welcome to the Zigbee Lighting Link (Ikea Tradfri) Hacking tool!")
print_info("By group 102 for Lab on offenive Computer Security.")
questions = [
    {
        'type': 'list',
        'name': 'command',
        'message': 'Choose somtething to do',
        'choices': [
            '1. Scan for Zigbee Networks', 
            '2. Extract key on device join', 
            '3. Spoof the gateway (toggle light)'
            ],
    },
    {
        'type': 'input',
        'name': 'channel',
        'message': 'Enter the Zigbee Channel to use:',
        'validate': NumberValidator,
        'filter': lambda val: int(val)
    },
    {
        'type': 'confirm',
        'name': 'wireshark',
        'message': 'Use Wireshark?',
        'default': False,
    }
]

answers = prompt(questions)
print_json(answers)  # use the answers as input for your app
